image: ruby:3.2.1

before_script:
  - chmod +x pipeline-assets/scripts/*
  - pipeline-assets/scripts/install-basic-libraries.sh
  - pipeline-assets/scripts/install-bundler.sh
  - pipeline-assets/scripts/install-chrome-browser.sh
  - pipeline-assets/scripts/install-chrome-driver.sh

stages:
  - testing

E2E-Testing:
  stage: testing
  script:
    - export now=$(date +"%Y-%m-%d_%H-%M-%S") && cucumber -f pretty -f html -o reports/$now.report.html
  artifacts:
    when: always
    expire_in: 4 days
    paths:
      - reports/
